// Сайтын бүх текст нэг дор. Үнэ, үйлчилгээ, туршлагыг энд л засна.
// Үнэ нь эхлэх үнэ (2026.09 судалгаанд үндэслэсэн санал) — зах зээлд туршиж тохируулна.

export const CONTACT = {
  phone: '89664270',
  phoneDisplay: '8966 4270',
  email: 'info@zangilaait.com',
};

export const SERVICE_KEYS = ['network', 'starlink', 'wifi', 'cctv', 'server', 'support', 'web', 'callout'];

const mn = {
  lang: 'mn',
  htmlLang: 'mn',
  brand: 'Зангилаа',
  title: 'Зангилаа | Байгууллагын сүлжээ, Starlink, вэбсайт',
  description: 'Сүлжээний инженер Ц.Золжаргал: байгууллагын дотоод сүлжээ, Wi-Fi, Starlink суурилуулалт, хяналтын камер, сервер болон вэбсайт. Хувь хүн, байгууллагад.',
  skip: 'Үндсэн хэсэг рүү шилжих',
  nav: { services: 'Үйлчилгээ', starlink: 'Starlink', examples: 'Жишээ сайт', about: 'Туршлага', order: 'Захиалах' },
  otherLang: { label: 'EN', href: '/en/', name: 'English' },
  hero: {
    h1: 'Байгууллагын сүлжээ, Starlink, вэбсайтыг нэг инженер хариуцна',
    lead: 'Интернэт үйлчилгээ үзүүлэгч болон төлбөрийн системийн компанид 5 жил сүлжээ, сервер хариуцсан туршлагаараа таны оффис, дэлгүүр, жуулчны баазын интернэт, Wi-Fi, камер, сайтыг найдвартай ажиллуулна.',
    cta: 'Захиалга өгөх',
    call: 'Залгах',
    diagramCaption: 'Таны сүлжээ ийм бүтэцтэй байж болно. Хэсэг дээр дарж дэлгэрэнгүйг үзээрэй.',
  },
  facts: [
    'ШУТИС, сүлжээний технологийн инженер',
    'Интернэт үйлчилгээ үзүүлэгч компанид 2021 оноос',
    'Төлбөрийн системийн компанид сүлжээний инженер',
  ],
  topo: {
    internet: 'Интернэт', starlink: 'Starlink', firewall: 'Firewall', switch: 'Свитч', web: 'Вэбсайт',
    wifi: 'Wi-Fi', cctv: 'Камер', server: 'Сервер', pc: 'Ажилтан', support: 'Сарын IT дэмжлэг бүгдийг хамарна',
  },
  servicesTitle: 'Үйлчилгээ',
  servicesLead: 'Эхлэх үнийг ил тавьсан. Тоног төхөөрөмж, материал тусдаа. Газар дээр нь үзсэний дараа тодорхой үнийн санал өгнө.',
  priceFrom: 'Эхлэх үнэ',
  orderThis: 'Энэ үйлчилгээг захиалах',
  services: {
    network: {
      title: 'Байгууллагын сүлжээ',
      lead: 'Оффис, дэлгүүр, агуулахын дотоод сүлжээг зураглалаас эхлээд угсралт хүртэл.',
      points: ['Cat6 кабель татах, цэг холбох, хурд шалгах', 'Роутер, свитч, VLAN: ажилтан, зочин, камерыг тусгаарлана', 'Firewall, VPN, гэрээс ажиллах алсын хандалт', 'Сүлжээний зураг, нууц үгийн бүртгэлийг хүлээлгэн өгнө'],
      price: 'Цэг бүр 30,000₮-с',
    },
    starlink: {
      title: 'Starlink суурилуулалт',
      lead: 'Орон нутаг, жуулчны бааз, барилгын талбай, фермд хиймэл дагуулын интернэт.',
      points: ['Дээвэр, багана, хананд бат бэхлэх, кабелийг цэвэр татах', 'Олон гэр, байшинг хамарсан Wi-Fi (mesh)', 'Одоо байгаа интернэттэй хослуулж автомат нөөц холболт', 'Цахилгаан тасрахад зориулсан UPS, хамгаалалт'],
      price: '150,000₮-с (төхөөрөмж тусдаа)',
    },
    wifi: {
      title: 'Wi-Fi сүлжээ',
      lead: 'Кафе, зочид буудал, оффисын бүх өрөөнд тасалдалгүй.',
      points: ['Дохионы хүчийг өрөө бүрт хэмжинэ', 'Access point байршуулалт, тохиргоо', 'Зочны сүлжээг тусад нь, хурдны хязгаартай'],
      price: '200,000₮-с',
    },
    cctv: {
      title: 'Хяналтын камер',
      lead: 'IP камер, бичлэгийн хадгалалт, утаснаас харах.',
      points: ['Байршил, өнцгийг төлөвлөж суурилуулна', 'Гар утаснаас алсаас шууд харах тохиргоо', 'Бичлэгийг хэдэн хоног хадгалахыг тооцож диск сонгоно'],
      price: 'Камер бүр 60,000₮-с',
    },
    server: {
      title: 'Сервер, үүлэн шийдэл',
      lead: 'Linux сервер, Docker, нөөцлөлт, хяналт.',
      points: ['Linux сервер суурилуулж, аюулгүй байдлыг бэхжүүлнэ', 'Docker, CI/CD автоматжуулалт', 'Өдөр тутмын нөөцлөлт, сэргээх туршилт', 'Мониторинг: асуудал гармагц мэдэгдэл ирнэ'],
      price: '300,000₮-с',
    },
    support: {
      title: 'Сарын IT дэмжлэг',
      lead: 'Асуудал гарахаас нь өмнө. Тогтмол үнэ, гэнэтийн зардалгүй.',
      points: ['Сар бүр урьдчилан сэргийлэх үзлэг', 'Утсаар, алсаас шуурхай тусламж', 'Тоног төхөөрөмж, лицензийн бүртгэл'],
      price: '10 хүртэл ажилтан: сард 350,000₮',
    },
    web: {
      title: 'Вэбсайт',
      lead: 'Жижиг бизнесийн сайт, цэс, үнээ өөрөө засдаг самбартай.',
      points: ['Салбарын бэлэн загвар: доорх жишээг сольж үзээрэй', 'Цэс, үнэ, цагийн хуваарийг өөрөө засна', 'Домэйн, SSL, хостинг багтсан'],
      price: '150,000₮ + сард 29,000₮-с',
    },
    callout: {
      title: 'Дуудлага, оношлогоо',
      lead: 'Интернэт тасарсан, сүлжээ удаан байна уу? Хот дотор очиж шалгана.',
      points: ['Шалтгааныг олж, засах арга, үнийг хэлнэ', 'Жижиг засварыг газар дээр нь хийнэ'],
      price: '30,000₮',
    },
  },
  starlink: {
    title: 'Хот хүрэхгүй газар ч хурдан интернэт',
    lead: 'Starlink-ийн тавагыг зүгээр тавихад ажилладаг. Харин салхинд унахгүй бэхлэх, хүйтэнд кабелийг хамгаалах, олон гэрт Wi-Fi түгээх, цахилгаан тасрахад ажиллуулах нь инженерийн ажил.',
    points: [
      ['Бэхэлгээ', 'Монголын салхи, цасанд тэсвэртэй багана, дээврийн бэхэлгээ'],
      ['Түгээлт', 'Нэг тавагаас олон гэр, байшинд mesh Wi-Fi'],
      ['Нөөц холболт', 'Мобайл эсвэл кабелийн интернэттэй хослуулж, аль нэг нь тасрахад автоматаар шилжинэ'],
      ['Хяналт', 'Хурд, тасалдлыг алсаас хянаж, асуудлыг эрт илрүүлнэ'],
    ],
    note: 'Төхөөрөмжийг албан ёсны борлуулагчаас авна. Сарын төлбөрийг Starlink-д шууд төлнө.',
  },
  processTitle: 'Ажил хэрхэн явагдах вэ',
  process: [
    ['Хүсэлт', 'Доорх формоор эсвэл утсаар хүсэлтээ үлдээнэ.'],
    ['Тодруулга', 'Утсаар ярьж хэрэгцээг тодруулна. Шаардлагатай бол газар дээр нь үзнэ.'],
    ['Үнийн санал', 'Ажил, материал, хугацааг бичгээр гаргаж өгнө.'],
    ['Гүйцэтгэл', 'Тохирсон хугацаанд хийж, хамт шалгана.'],
    ['Хүлээлгэн өгөх', 'Сүлжээний зураг, нууц үг, зааврыг өгнө. Баталгаат хугацаанд үнэгүй засна.'],
  ],
  examplesTitle: 'Бидний хийдэг вэбсайт',
  examplesLead: 'Салбараа сонгоод бүтэц, өнгийг нь сольж үзээрэй. Бүгд утсан дээр зөв харагдана, эзэмшигч нь цэс, үнээ өөрөө засна.',
  examplesLayout: 'Бүтэц',
  examplesPalette: 'Өнгө',
  examplesOpen: 'Бүтэн дэлгэцээр нээх',
  examplesOrder: 'Энэ загвараар сайт захиалах',
  examplesFrameTitle: 'Жишээ вэбсайт',
  layouts: { menu: 'Жагсаалт', poster: 'Постер', card: 'Карт' },
  aboutTitle: 'Туршлага',
  aboutName: 'Ц.Золжаргал',
  aboutRole: 'Сүлжээний инженер, системийн админ',
  aboutText: '2021 онд ШУТИС-ийн Мэдээлэл, холбооны технологийн сургуулийг сүлжээний технологийн чиглэлээр төгссөн. Сүлжээ, системийн найдвартай ажиллагаа, аюулгүй байдлыг хариуцаж ирсэн. 3 хүнтэй баг удирдаж байсан.',
  timeline: [
    ['2025–', 'Сүлжээний инженер', 'Төлбөрийн системийн компани'],
    ['2021–', 'Системийн админ', 'Интернэт үйлчилгээ үзүүлэгч компани'],
    ['2021', 'Бакалавр, сүлжээний технологи', 'ШУТИС, МХТС'],
    ['2020', 'Судлаач оюутан, сүлжээний тоног төхөөрөмж', 'Арилжааны банк'],
  ],
  skillsTitle: 'Ур чадвар',
  skills: ['Сүлжээний дизайн, архитектур', 'Сүлжээний аюулгүй байдал', 'Мониторинг', 'Хандалтын удирдлага', 'Үүлэн сүлжээ', 'Linux', 'Docker', 'CI/CD'],
  orderTitle: 'Захиалга өгөх',
  orderLead: 'Хүсэлтээ үлдээгээрэй, удалгүй утсаар холбогдоно. Яаралтай бол шууд залгаарай.',
  form: {
    type: 'Та хэн бэ?', person: 'Хувь хүн', org: 'Байгууллага',
    service: 'Үйлчилгээ', name: 'Нэр', phone: 'Утас', orgName: 'Байгууллагын нэр',
    location: 'Байршил', locationHint: 'Дүүрэг, хороо эсвэл аймаг, сум',
    message: 'Юу хэрэгтэй байна вэ?', messageHint: 'Жишээ: 12 ажилтантай оффис, Wi-Fi тасраад байна',
    submit: 'Хүсэлт илгээх', sending: 'Илгээж байна…',
    ok: 'Хүсэлт хүлээн авлаа. Удалгүй утсаар холбогдоно.',
    error: 'Илгээж чадсангүй. Дахин оролдох эсвэл 8966 4270 дугаарт залгана уу.',
    other: 'Бусад',
  },
  direct: 'Шууд холбогдох',
  footer: 'Байгууллагын сүлжээ, Starlink, вэбсайт. Улаанбаатар болон орон нутагт.',
};

const en = {
  lang: 'en',
  htmlLang: 'en',
  brand: 'Zangilaa',
  title: 'Zangilaa | Business networks, Starlink and websites in Mongolia',
  description: 'Network engineer Zoljargal Ts.: office networks, Wi-Fi, Starlink installation, CCTV, servers and websites for individuals and organizations in Mongolia.',
  skip: 'Skip to main content',
  nav: { services: 'Services', starlink: 'Starlink', examples: 'Website examples', about: 'Experience', order: 'Get a quote' },
  otherLang: { label: 'МН', href: '/', name: 'Монгол' },
  hero: {
    h1: 'One engineer for your network, Starlink and website',
    lead: 'Five years running networks and servers at an internet service provider and a payment systems company. I make the internet, Wi-Fi, cameras and website at your office, shop or tourist camp work reliably.',
    cta: 'Request a quote',
    call: 'Call',
    diagramCaption: 'Your network could look like this. Tap any part to see the service.',
  },
  facts: [
    'Network engineering degree, MUST',
    'At an internet service provider since 2021',
    'Network engineer at a payment systems company',
  ],
  topo: {
    internet: 'Internet', starlink: 'Starlink', firewall: 'Firewall', switch: 'Switch', web: 'Website',
    wifi: 'Wi-Fi', cctv: 'Cameras', server: 'Server', pc: 'Staff PCs', support: 'Monthly IT support covers it all',
  },
  servicesTitle: 'Services',
  servicesLead: 'Starting prices are public. Equipment and materials are extra. You get an exact quote after a site visit. Prices in Mongolian tögrög (MNT).',
  priceFrom: 'From',
  orderThis: 'Request this service',
  services: {
    network: {
      title: 'Office networks',
      lead: 'Wired networks for offices, shops and warehouses, from planning to installation.',
      points: ['Cat6 cabling, termination and speed testing', 'Routers, switches, VLANs separating staff, guests and cameras', 'Firewall, VPN and secure remote access', 'You receive a network diagram and credential register'],
      price: '30,000₮ per drop',
    },
    starlink: {
      title: 'Starlink installation',
      lead: 'Satellite internet for the countryside, tourist camps, construction sites and farms.',
      points: ['Secure roof, pole or wall mounts with clean cable runs', 'Mesh Wi-Fi across several gers and buildings', 'Automatic failover together with your existing internet', 'UPS and surge protection for power cuts'],
      price: '150,000₮ (equipment extra)',
    },
    wifi: {
      title: 'Wi-Fi networks',
      lead: 'Seamless coverage in every room of a café, hotel or office.',
      points: ['Signal survey room by room', 'Access point placement and configuration', 'Separate, rate-limited guest network'],
      price: '200,000₮',
    },
    cctv: {
      title: 'CCTV cameras',
      lead: 'IP cameras, recording storage and viewing from your phone.',
      points: ['Planned placement and viewing angles', 'Live remote viewing on your phone', 'Storage sized for how many days you keep'],
      price: '60,000₮ per camera',
    },
    server: {
      title: 'Servers and cloud',
      lead: 'Linux servers, Docker, backups and monitoring.',
      points: ['Linux server setup and hardening', 'Docker and CI/CD automation', 'Daily backups with restore tests', 'Monitoring with instant alerts'],
      price: '300,000₮',
    },
    support: {
      title: 'Monthly IT support',
      lead: 'Before problems happen. A fixed fee, no surprise bills.',
      points: ['Monthly preventive check-up', 'Fast help by phone and remotely', 'Equipment and licence inventory'],
      price: 'Up to 10 staff: 350,000₮ / month',
    },
    web: {
      title: 'Websites',
      lead: 'Small business websites with a dashboard to edit menus and prices yourself.',
      points: ['Industry templates: try the examples below', 'Edit menus, prices and opening hours yourself', 'Domain, SSL and hosting included'],
      price: '150,000₮ + 29,000₮ / month',
    },
    callout: {
      title: 'Call-out and diagnosis',
      lead: 'Internet down or slow network? I come on site in Ulaanbaatar.',
      points: ['Find the cause, explain the fix and the price', 'Small repairs done on the spot'],
      price: '30,000₮',
    },
  },
  starlink: {
    title: 'Fast internet where cables don\'t reach',
    lead: 'A Starlink dish works when you set it down. Keeping it standing in Mongolian wind, protecting cables in the cold, sharing Wi-Fi across gers and staying online through power cuts is engineering work.',
    points: [
      ['Mounting', 'Pole and roof mounts built for Mongolian wind and snow'],
      ['Coverage', 'Mesh Wi-Fi from one dish to several gers and buildings'],
      ['Failover', 'Paired with mobile or cable internet, switching automatically when one drops'],
      ['Monitoring', 'Remote speed and outage monitoring to catch issues early'],
    ],
    note: 'Equipment comes from authorized resellers. You pay the monthly plan directly to Starlink.',
  },
  processTitle: 'How it works',
  process: [
    ['Request', 'Leave a request with the form below or by phone.'],
    ['Clarify', 'We talk through your needs by phone, with a site visit if needed.'],
    ['Quote', 'You get the work, materials and timeline in writing.'],
    ['Delivery', 'Done on the agreed schedule and tested together.'],
    ['Handover', 'You receive the network diagram, credentials and instructions. Free fixes during the warranty.'],
  ],
  examplesTitle: 'Websites we build',
  examplesLead: 'Pick an industry, then switch the layout and colours. Every site works on phones, and owners edit their own menus and prices. Examples are in Mongolian.',
  examplesLayout: 'Layout',
  examplesPalette: 'Colours',
  examplesOpen: 'Open full screen',
  examplesOrder: 'Order a site like this',
  examplesFrameTitle: 'Example website',
  layouts: { menu: 'List', poster: 'Poster', card: 'Cards' },
  aboutTitle: 'Experience',
  aboutName: 'Zoljargal Tserendagva',
  aboutRole: 'Network engineer, system administrator',
  aboutText: 'Graduated in network technology from the Mongolian University of Science and Technology in 2021. I have been responsible for the reliability and security of networks and systems, and have led a team of three.',
  timeline: [
    ['2025–', 'Network engineer', 'Payment systems company'],
    ['2021–', 'System administrator', 'Internet service provider'],
    ['2021', 'BSc, network technology', 'MUST, School of ICT'],
    ['2020', 'Research student, network equipment', 'Commercial bank'],
  ],
  skillsTitle: 'Skills',
  skills: ['Network design and architecture', 'Network security', 'Monitoring', 'Access control', 'Cloud networking', 'Linux', 'Docker', 'CI/CD'],
  orderTitle: 'Request a quote',
  orderLead: 'Leave your details and I will call you back soon. For urgent issues, call directly.',
  form: {
    type: 'Who are you?', person: 'Individual', org: 'Organization',
    service: 'Service', name: 'Name', phone: 'Phone', orgName: 'Organization name',
    location: 'Location', locationHint: 'District or province',
    message: 'What do you need?', messageHint: 'Example: office with 12 staff, Wi-Fi keeps dropping',
    submit: 'Send request', sending: 'Sending…',
    ok: 'Request received. I will call you back soon.',
    error: 'Could not send. Try again or call 8966 4270.',
    other: 'Other',
  },
  direct: 'Contact directly',
  footer: 'Business networks, Starlink and websites. Ulaanbaatar and the countryside.',
};

export const LANGS = { mn, en };
